In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [14]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

/home/soham/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9703703703703703

In [15]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9814814814814815

In [16]:
# do the same for random forest
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9722222222222222

In [17]:
kf = KFold(n_splits=4)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [19]:
df = pd.DataFrame(digits.data)

In [20]:
df = pd.concat([df,pd.DataFrame(digits.target,columns=['digit'])],axis='columns')

In [21]:
df

0    1     2     3     4     5    6    7    8    9  ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63  digit  
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0      0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0      1  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0      2  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0      3  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0      4  
...   ...  ...   ...   ...   ...  ...  ...    ...  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0      9  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0      0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0      8  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0      9  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0      8  

[1797 rows x 65 columns]

In [23]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [29]:
split_val = 3
total = 0
for train_index,test_index in kf.split(df):
    x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)
    total += get_score(rf,x_train,x_test,y_train,y_test)
avg = total/split_val
print(avg) 

0.9709876543209877


In [31]:
from sklearn.model_selection import  StratifiedKFold

skf = StratifiedKFold(n_splits=3)

In [38]:
score_lr = []
score_svm = []
score_rf = []
for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_lr.append(get_score(lr,x_train,x_test,y_train,y_test))
    score_svm.append(get_score(svm,x_train,x_test,y_train,y_test))
    score_rf.append(get_score(rf,x_train,x_test,y_train,y_test))
print(score_lr)
print(score_svm)
print(score_rf)

/home/soham/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/soham/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
[0.9482470784641068, 0.9515859766277128, 0.9315525876460768]


In [39]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]
